--Ibrahim Fleury de Camargo Madeira Neto / 25014766
--Thiago Viel Denadai / 25004361
--Vinícius Logatto Costa Sete / 25003510


CREATE TABLE categoria (
  id_categoria    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            VARCHAR2(80) NOT NULL
);

CREATE TABLE fornecedor (
  id_fornecedor   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            VARCHAR2(120) NOT NULL,
  telefone        VARCHAR2(20)  -- pode ser NULL
);

CREATE TABLE produto (
  id_produto        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome              VARCHAR2(120) NOT NULL,
  sku               VARCHAR2(20)  NOT NULL UNIQUE,
  preco             NUMBER(10,2)  NOT NULL CHECK (preco >= 0),
  desconto_percent  NUMBER(5,2),              -- pode ser NULL
  estoque           NUMBER(10)    DEFAULT 0   NOT NULL,
  data_cadastro     DATE          DEFAULT SYSDATE NOT NULL,
  descontinuado_em  DATE,                      -- pode ser NULL
  id_categoria      NUMBER NOT NULL,
  id_fornecedor     NUMBER NOT NULL,
  CONSTRAINT fk_prod_cat FOREIGN KEY (id_categoria)  REFERENCES categoria(id_categoria),
  CONSTRAINT fk_prod_forn FOREIGN KEY (id_fornecedor) REFERENCES fornecedor(id_fornecedor)
);

CREATE TABLE cliente (
  id_cliente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           VARCHAR2(120) NOT NULL,
  cpf            VARCHAR2(11)  NOT NULL,    -- guardado sem formatação
  telefone       VARCHAR2(20),               -- pode ser NULL
  email          VARCHAR2(120)
);

CREATE TABLE pedido (
  id_pedido     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente    NUMBER       NOT NULL,
  data_pedido   DATE         DEFAULT SYSDATE NOT NULL,
  status        VARCHAR2(20) DEFAULT 'ABERTO' NOT NULL,
  observacoes   VARCHAR2(200),               -- pode ser NULL
  CONSTRAINT fk_ped_cli FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

CREATE TABLE item_pedido (
  id_pedido     NUMBER NOT NULL,
  id_produto    NUMBER NOT NULL,
  qtd           NUMBER(10,2) NOT NULL CHECK (qtd > 0),
  preco_unit    NUMBER(10,2) NOT NULL CHECK (preco_unit >= 0),
  desconto_item NUMBER(5,2),                 -- pode ser NULL
  CONSTRAINT pk_item_pedido PRIMARY KEY (id_pedido, id_produto),
  CONSTRAINT fk_item_ped  FOREIGN KEY (id_pedido)  REFERENCES pedido(id_pedido),
  CONSTRAINT fk_item_prod FOREIGN KEY (id_produto) REFERENCES produto(id_produto)
);

-- Dados de exemplo

INSERT INTO categoria (nome) VALUES ('Informática');
INSERT INTO categoria (nome) VALUES ('Escritório');
INSERT INTO categoria (nome) VALUES ('Acessórios');

INSERT INTO fornecedor (nome, telefone) VALUES ('Tech Distribuidora', '193333-0001');
INSERT INTO fornecedor (nome, telefone) VALUES ('Global Office',    NULL);        -- telefone NULL
INSERT INTO fornecedor (nome, telefone) VALUES ('MaxParts',         '112222-9999');

INSERT INTO produto (nome, sku, preco, desconto_percent, estoque, id_categoria, id_fornecedor, descontinuado_em)
VALUES ('Notebook Pro 14', 'NBP14-001', 6500.00, NULL,  15, 1, 1, NULL);

INSERT INTO produto (nome, sku, preco, desconto_percent, estoque, id_categoria, id_fornecedor)
VALUES ('Mouse Óptico', 'MOU-100', 60.00, 5, 120, 3, 3);

INSERT INTO produto (nome, sku, preco, desconto_percent, estoque, id_categoria, id_fornecedor)
VALUES ('Teclado Mecânico', 'TEK-200', 350.00, NULL, 40, 3, 3);

INSERT INTO produto (nome, sku, preco, desconto_percent, estoque, id_categoria, id_fornecedor, descontinuado_em)
VALUES ('Impressora Laser', 'IMP-500', 1200.00, 10, 5, 2, 2, TO_DATE('2025-12-31','YYYY-MM-DD'));

INSERT INTO produto (nome, sku, preco, desconto_percent, estoque, id_categoria, id_fornecedor)
VALUES ('Monitor 24"', 'MON-24FHD', 899.90, NULL, 22, 1, 1);

INSERT INTO cliente (nome, cpf, telefone, email) VALUES ('Ana Silva',    '12345678901', '1998888-7777', 'ana@ex.com');
INSERT INTO cliente (nome, cpf, telefone, email) VALUES ('Bruno Costa',  '98765432100', NULL,            'bruno@ex.com');  -- telefone NULL
INSERT INTO cliente (nome, cpf, telefone, email) VALUES ('Carla Mendes', '45678912300', '1199999-0000', 'carla@ex.com');

INSERT INTO pedido (id_cliente, data_pedido, status, observacoes)
VALUES (1, TRUNC(SYSDATE)-10, 'FECHADO', 'Compra online');

INSERT INTO pedido (id_cliente, data_pedido, status)
VALUES (2, TRUNC(SYSDATE)-2, 'ABERTO');

INSERT INTO item_pedido (id_pedido, id_produto, qtd, preco_unit, desconto_item)
VALUES (1, 1, 1, 6500.00, NULL);

INSERT INTO item_pedido (id_pedido, id_produto, qtd, preco_unit, desconto_item)
VALUES (1, 2, 2, 60.00,  0);

INSERT INTO item_pedido (id_pedido, id_produto, qtd, preco_unit, desconto_item)
VALUES (2, 5, 1, 899.90, NULL);

COMMIT;

/* 1) Crie uma trigger chamada trg_verifica_preco_produto que seja executada antes de inserir 
um novo registro na tabela produto. A trigger deve verificar se o valor do campo preco é 
menor que 50. Caso seja, a trigger deve gerar um erro utilizando RAISE_APPLICATION_ERROR 
com uma mensagem informando que "O preço mínimo permitido para um produto é R$50,00".
*/

CREATE OR REPLACE TRIGGER trg_verifica_preco_produto
BEFORE INSERT ON produto
FOR EACH ROW
BEGIN
    IF :NEW.preco < 50 THEN
        RAISE_APPLICATION_ERROR(-20001, 'O preço mínimo permitido para um produto é R$50,00');
    END IF;
END;

/* ----------------------------------------------------------------------------------- */

/* 2) Crie uma trigger chamada trg_registra_entrada_estoque que seja executada após a inserção 
de um novo item na tabela item_pedido. A trigger deve diminuir a quantidade (qtd) do produto 
correspondente na tabela produto, atualizando o campo estoque.
*/

CREATE OR REPLACE TRIGGER trg_registra_entrada_estoque
AFTER INSERT ON item_pedido
FOR EACH ROW
BEGIN
    UPDATE produto
    SET estoque = estoque - :NEW.qtd
    WHERE id_produto = :NEW.id_produto;
END;


/* ----------------------------------------------------------------------------------- */

/* 3) Crie uma trigger chamada trg_bloqueia_update_descontinuado que seja executada antes de 
atualizar registros da tabela produto. A trigger deve impedir qualquer atualização em produtos 
cujo campo descontinuado_em não seja nulo. Utilize RAISE_APPLICATION_ERROR com uma mensagem 
apropriada, como "Produtos descontinuados não podem ser alterados."
*/

CREATE OR REPLACE TRIGGER trg_bloqueia_update_descontinuado
BEFORE UPDATE ON produto
FOR EACH ROW
BEGIN
    IF :OLD.descontinuado_em IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'Produtos descontinuados não podem ser alterados.');
    END IF;
END;
/

/* ----------------------------------------------------------------------------------- */

/* 4) Crie uma tabela auxiliar chamada log_preco_produto com os campos: id_log, id_produto, 
preco_antigo, preco_novo, data_alteracao com valor default com a data do sistema. 
Em seguida, crie uma trigger chamada trg_log_alteracao_preco que seja executada após 
atualizar registros da tabela produto. A trigger deve inserir um registro em log_preco_produto 
somente quando o valor de preco for alterado.
*/

CREATE TABLE log_preco_produto (
    id_log NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_produto NUMBER,
    preco_antigo NUMBER(10,2),
    preco_novo NUMBER(10,2),
    data_alteracao DATE DEFAULT SYSDATE
);

CREATE OR REPLACE TRIGGER trg_log_alteracao_preco
AFTER UPDATE ON produto
FOR EACH ROW
BEGIN
    IF :NEW.preco <> :OLD.preco THEN
        INSERT INTO log_preco_produto (id_produto, preco_antigo, preco_novo)
        VALUES (:NEW.id_produto, :OLD.preco, :NEW.preco);
    END IF;
END;

/* ----------------------------------------------------------------------------------- */

/* 5) Crie uma trigger chamada trg_bloqueia_exclusao_pedido que seja executada antes de deletar 
um registro da tabela pedido. A trigger deve verificar se o campo status do pedido é igual 
a 'FECHADO'. Caso seja, deve impedir a exclusão com RAISE_APPLICATION_ERROR(-20001, 
'Pedidos fechados não podem ser excluídos.');
*/

CREATE OR REPLACE TRIGGER trg_bloqueia_exclusao_pedido
BEFORE DELETE ON pedido
FOR EACH ROW
BEGIN
    IF :OLD.status = 'FECHADO' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Pedidos fechados não podem ser excluídos.');
    END IF;
END;


/* ----------------------------------------------------------------------------------- */

/* 6) Crie uma tabela chamada produto_excluido com a estrutura: id_produto, nome, sku, preco, 
data_exclusao com valor default com a data do sistema. Em seguida, crie uma trigger chamada 
trg_registra_exclusao_produto que seja executada após a exclusão de um registro da tabela 
produto. A trigger deve inserir um registro em produto_excluido com os valores do produto 
removido (:OLD), registrando automaticamente a data da exclusão.
*/

CREATE TABLE produto_excluido (
    id_produto NUMBER,
    nome VARCHAR2(120),
    sku VARCHAR2(20),
    preco NUMBER(10,2),
    data_exclusao DATE DEFAULT SYSDATE
);

CREATE OR REPLACE TRIGGER trg_registra_exclusao_produto
AFTER DELETE ON produto
FOR EACH ROW
BEGIN
    INSERT INTO produto_excluido (id_produto, nome, sku, preco)
    VALUES (:OLD.id_produto, :OLD.nome, :OLD.sku, :OLD.preco);
END;